# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: CrackenReleased.BoarderlessMCP
PackageVersion: 0.1.29
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/CrackenReleased/boarderless.app_MCP/releases/download/v0.1.29/Boarderless.MCP_0.1.29_x64-setup.exe
    InstallerSha256: 1C0A4E60D64ADA2600260B93EFE8E5EC87127130B5CB25015C024155A4B0DD1D
    InstallerType: nullsoft
ManifestType: installer
ManifestVersion: 1.9.0
